name: Deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 21098
        script: |
          uapi --output=jsonpretty \
          SubDomain \
          addsubdomain \
          domain='autotest.prismaticcrm.com' \
          rootdomain='prismaticcrm.com'
          cd autotest.prismaticcrm.com
          git clone https://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@github.com/kashif-pris/getmover.git
          composer install
          touch .env
          echo "APP_NAME='GetMovers'
                APP_ENV=local
                APP_KEY=base64:Sbg4BcMfF59yfJEZiqyqvXfS/OKDCbOFNNPs7C5bHaQ=
                APP_DEBUG=true
                APP_LOG_LEVEL=debug
                APP_URL='https://autotest.prismaticcrm.com/public/storage/'
                
                
                DB_CONNECTION=mysql
                DB_HOST=127.0.0.1
                DB_PORT=3306
                DB_DATABASE=priscjsz_autotest
                DB_USERNAME=priscjsz_autotest_user
                DB_PASSWORD=autotest_user
                
                BROADCAST_DRIVER=log
                CACHE_DRIVER=file
                SESSION_DRIVER=file
                QUEUE_DRIVER=sync
                
                REDIS_HOST=127.0.0.1
                REDIS_PASSWORD=null
                REDIS_PORT=6379
                
                MAIL_DRIVER="smtp"
                MAIL_HOST="prismaticcrm.com"
                MAIL_PORT="465"
                mail_username="techzologytesting@prismatic-technologies.com"
                MAIL_PASSWORD="techzology"
                MAIL_ENCRYPTION="ssl"
                mail_from_address="techzologytesting@prismatic-technologies.com"
                MAIL_FROM_NAME="Quest for Exams"
                
                PUSHER_APP_ID=
                PUSHER_APP_KEY=
                PUSHER_APP_SECRET=
                APP_NAME='GETMOVERS'
                APP_NAME='GETMOVERS'
                APP_NAME='GETMOVERS'
                APP_NAME='GETMOVERS'
                APP_NAME='GETMOVERS'
                CAPTCHA_SITEKEY=''
                CAPTCHA_SECRET=''
                
                STRIPE_KEY=pk_test_51Hla3sJbeDo0wh2dUz61eCPFRon7FP1ryS6eQjnkmwPSopGofXx8ixqehkGtTaHxEa7p6R2mXzfEGVOrWo0U6zaQ00mfd2Y5Ce
                STRIPE_SECRET=sk_test_51Hla3sJbeDo0wh2dkkpUvDGfNN4pgcC7jjQIeTZwm5cSJzBgGPFyFDRs8Lgs3KAbr9SWgWeckVLukB4zxf025qeg00KxIqryLt " > .env
                mv priscddb_luggage.sql /home/priscjsz
                cd ..
                uapi --output=jsonpretty Batch strict command-0='[ "Mysql", "create_database", {"name":"priscjsz_autotest"}]' command-1='[ "Mysql", "create_user", {"name":"priscjsz_autotest_user", "password":"autotest_user"}]' command-2='[ "Mysql", "set_privileges_on_database",{"user":"priscjsz_autotest_user", "database":"priscjsz_autotest", "privileges":"ALL PRIVILEGES"}]'
                mysql -u priscjsz_autotest_user priscjsz_autotest -p'autotest_user' < priscddb_luggage.sql
