name: Deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 21098
        script: |
          mysql -u priscjsz -p'JSQfNZD0p8lQ' -e "CREATE DATABASE testauto;"
          mysql -u priscjsz -p'JSQfNZD0p8lQ' -D testauto < priscjsz_optimus.sql
