name: Deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 21098
        script: |
          uapi --output=jsonpretty \
          SubDomain \
          addsubdomain \
          domain='autotest.prismaticcrm.com' \
          rootdomain='prismaticcrm.com'
          cd autotest.prismaticcrm.com
          touch index.html
          echo "kashif ali" > filename.txt
